version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: tekflix_db
      POSTGRES_USER: tekflix_user
      POSTGRES_PASSWORD: tekflix_pass
    ports:
      - "5432:5432"

  web:
    build: .
  
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: '1'
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
      DB_NAME: tekflix_db
      DB_USER: tekflix_user
      DB_PASSWORD: tekflix_pass
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data:
