# Generated by Django 5.2.4 on 2025-07-20 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LLM", "0003_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={},
        ),
        migrations.AddField(
            model_name="topic",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="LLM.category",
            ),
        ),
    ]
