# Generated by Django 5.1.3 on 2025-07-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LLM", "0004_alter_topic_options_topic_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="project",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="category",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["order", "created_at"]},
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
